### ISSUE TITLE
Results and configs of COCO

### ISSUE THREAD

**Issue by dangelosue** [yhcao6/FADI#2]
Hey there. Thanks a lot for the quality codes!
It seems like you guys are only releasing the configs and models of VOC.
Is it available to access the COCO counterparts?

**Comment by yhcao6** [comment]
Thanks for your interest in our work. 
FADI's advantage is announced mainly on the Pascal VOC dataset, hence we release the configs on Pascal VOC for reference.
We will further release the code of COCO later once we have spare time, but the implementation is almost the same as it on Pascal VOC.

**Comment by dangelosue** [comment]
Ok. Thanks.
